### DISCUSSION TITLE
Breakpoints

### DISCUSSION THREAD

**Discussion by KutnerUri** [teambit/design#21] [Ideas]
breakpoints pains:
- having too many breakpoints is bad for browser performance (each value is an window size observer)
- having too many breakpoints is bad for UX consistency (different elements will change in different sizes)
- media queries behavior is  hard to override

breakpoint goals:
- minimal palette of breakpoints that everyone could use
- consistent breakpoints throughout the system
- ~~overridable breakpoints~~ (not possible with today's technology)
- use vanilla technology as much as possible (don't bind to a specific technology)
- support browsers in the last 5 years (minimum)

## Existing code:

the existing breakpoints are:
```scss
$br-xs: 360px;
$br-sm: 480px;	//mobile
$br-md: 768px;
$br-l: 920px;	//tablet
$br-lg: 1200px;
$br-xl: 1440px;
$br-xxl: 1920px;
```

We researched them here:
![Screen Shot 2022-03-22 at 20 05 38](https://user-images.githubusercontent.com/5400361/159546811-85c820ac-c4de-4a43-9884-cdfe93196e3a.png)

### Existing usage:
Importing and using these variables is straight forward:

```scss
// import includes all variables from the target file
@import '~@teambit/design.PACKAGE.NAME/_breakpoints.scss';

// hide in mobile
@media screen and (max-width: $br-sm) {
  display: none;
}
```

#### File name:
We are forced to use `/_breakpoints.scss`, because Bit automatically sets `dist/index.js` as main file.
--> ⚠️ if bit allows setting a custom main file, we won't need to include the `/_breakpoints.scss` in the `@import`

The underscore (`_`) signifies internal file in sass.

**Comment by odedre** [comment]
### update: I think we should go with the mixin option below. some of these options are technically possible but bad, some dont really work 

did some research and so far I can see a few interesting but bad approaches:
- post css vars (with `@custom-media`): using `postcss-custom-media` plugin
    - we dont need to use `@import` in order to use the breakpoints
    - it might not work for apps/components that are not using post css

- defining css vars and using sass vars in order to share them
    - will work only for apps/components using sass
    - every app/component with media queries needs to `@import` the component.
    - we are using internal paths to access the scss file, which is not really supported by bit (but not enforced because its in css)

- using js media queries / hook / context (all using `window.matchMedia`)
    - easily sharable
    - might cause performance issues
    - harder to use along with css styles
    - easily use css vars breakpoints directly

- container queries
    - still in proposal stage
    - might be some polyfills for this but seems a bit early and can break easily
- creating a media query component along with the `max-width:..` part.
    - this will allow us to use css vars in this file and use the sass var to define it in the media query.
    - has the same issues as sharing the sass vars.~~

**Comment by KutnerUri** [comment]
## Option: new sass syntax

Sass now has a new, better syntax - `@use`

```scss
@use "~@teambit/design.PACKAGE.NAME/_breakpoints.scss";

// maybe we can drop the `$br` in this syntax
@media screen and (max-width: breakpoints.$br-sm) {
  display: none;
}
```

We can also create mixins for media queries.
This is probably not a good idea because it will make us more coupled to scss.
```scss
@mixin media($breakpoint) {
  @media only screen and (max-width: $breakpoint) {
     @content;
  }
}

// usage:
.main {
  background: red;

  // etc
  @include media($br-sm) {
    background: blue;
  }
}

// or create a convenience mixin:
@mixin media-sm {
  @include media($br-sm) {
    @content;
  }
}

// and use like so:
@include media-sm {
  background: blue;
}
```
## Javascript api
We should expose the variables via javascript. It can be done easily with css variables

```scss
// _breakpoints
:export {
  sm: $sm,
  md: $md,
  l: $l,
  lg: $lg,
  xl: $xl,
  xxl: $xxl,
}
```

```ts
// index.ts
export { sm, md, l, lg, xl, xxl } from './_breakpoints;
```

**Comment by KutnerUri** [comment]
## templating with sass `!default` values:

We can use [sass default values](https://sass-lang.com/documentation/variables#default-values) to create a custom breakpoint component, like so:

```scss
// breakpoints-template.scss
$xs: 360px !default;
$sm: 480px !default;
$md: 768px !default;
$l: 920px !default;
$lg: 1200px !default;
$xl: 1440px !default;
$xxl: 1920px !default;

// awesomebreakpoints.scss
@use "~@teambit/design.PACKAGE.NAME/_breakpoints.scss" with (
 $sm: 485px
)

// usage:
// repsonsive-button.module.scss
@use '.../awesomebreakpoints.scss"

// hide in mobile
@media screen and (max-width: awesomebreakpoints.$sm) {
  display: none;
}
```

This is not recommended, because it might fragment and increase the number of breakpoints in a component space.
